DROP DATABASE IF EXISTS PracSys;
CREATE DATABASE PracSys;
USE PracSys;

CREATE TABLE Account(
	Username VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Email VARCHAR(100),
	Name VARCHAR(100) NOT NULL,
	ContactNumber VARCHAR(20),
	Type VARCHAR(20),
	PRIMARY KEY(Username)
);

CREATE TABLE Company(
	Name VARCHAR(50) NOT NULL,
	MailingAddress VARCHAR(100) NOT NULL,
	PhoneNumber VARCHAR(20) NOT NULL,
	PRIMARY KEY(Name)
);

CREATE TABLE Account_Mentor(
	Username VARCHAR(50) NOT NULL,
	Company VARCHAR(50) NOT NULL,
	Title VARCHAR(50) NOT NULL,
	Department VARCHAR(50) NOT NULL,
	PRIMARY KEY(Username),
	FOREIGN KEY(Username) REFERENCES Account(Username) ON DELETE CASCADE,
	FOREIGN KEY(Company) REFERENCES Company(Name) ON DELETE CASCADE
);

CREATE TABLE Account_Student(
	Username VARCHAR(50) NOT NULL,
	IDNumber INT(6) NOT NULL,
	Mentor VARCHAR(50),
	Course VARCHAR(10) NOT NULL,
	PRIMARY KEY(Username),
	FOREIGN KEY(Username) REFERENCES Account(Username) ON DELETE CASCADE,
	FOREIGN KEY(Mentor) REFERENCES Account_Mentor(Username) ON DELETE CASCADE
);

CREATE TABLE Account_Faculty(
	Username VARCHAR(50) NOT NULL,
	IDNumber INT(6) NOT NULL,
	PRIMARY KEY(Username),
	FOREIGN KEY(Username) REFERENCES Account(Username) ON DELETE CASCADE
);

CREATE TABLE Form(
	ID INT(5) AUTO_INCREMENT NOT NULL,
	Name VARCHAR(100) NOT NULL,
	AccountPath VARCHAR(5) NOT NULL, 
	Active BOOLEAN NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE FormInstance(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	Username VARCHAR(50) NOT NULL,
	FormID INT(5) NOT NULL,
	Step INT(1) NOT NULL,
	LastResponse BOOLEAN NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(Username) REFERENCES Account_Student(Username),
	FOREIGN KEY(FormID) REFERENCES Form(ID) ON DELETE CASCADE
);

CREATE TABLE Comments(
	ID INT(5) AUTO_INCREMENT NOT NULL,
	InstanceID INT(6) NOT NULL,
	FormStep INT(1) NOT NULL,
	Text VARCHAR(10000) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(InstanceID) REFERENCES FormInstance(ID) ON DELETE CASCADE
);

CREATE TABLE Element(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	FormID INT(5) NOT NULL,
	ElementType VARCHAR(20) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(10000) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(FormID) REFERENCES Form(ID) ON DELETE CASCADE
);

CREATE TABLE Answer(
	ElementID INT(6) NOT NULL,
	InstanceID INT(6) NOT NULL,
	Param1 INT(6),
	Param2 INT(6),
	Val VARCHAR(10000) NOT NULL,
	PRIMARY KEY(ElementID, InstanceID, Param1, Param2),
	FOREIGN KEY(ElementID) REFERENCES Element(ID) ON DELETE CASCADE,
	FOREIGN KEY(InstanceID) REFERENCES FormInstance(ID) ON DELETE CASCADE
);

CREATE TABLE Element_PlainText(
	ID INT(6) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID) ON DELETE CASCADE
);

CREATE TABLE Element_Field(
	ID INT(6) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID) ON DELETE CASCADE
);

CREATE TABLE Element_TextArea(
	ID INT(6) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID) ON DELETE CASCADE
);

CREATE TABLE Element_DropDown(
	ID INT(6) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID) ON DELETE CASCADE
);

CREATE TABLE Element_DropDown_Choice(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	ElementID INT(6) NOT NULL,
	Choice VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ElementID) REFERENCES Element_DropDown(ID) ON DELETE CASCADE
);

CREATE TABLE Element_RadioCluster(
	ID INT(6) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID) ON DELETE CASCADE
);

CREATE TABLE Element_RadioCluster_Section(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	ElementID INT(6) NOT NULL,
	HasButtons BOOLEAN NOT NULL,
	Text VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ElementID) REFERENCES Element_RadioCluster(ID) ON DELETE CASCADE
);

CREATE TABLE Element_RadioCluster_Header(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	ElementID INT(6) NOT NULL,
	Text VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ElementID) REFERENCES Element_RadioCluster(ID) ON DELETE CASCADE
);

CREATE TABLE Element_Table(
	ID INT(6) NOT NULL,
	HasRowText BOOLEAN NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID) ON DELETE CASCADE
);

CREATE TABLE Element_Table_Row(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	ElementID INT(6) NOT NULL,
	Text VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ElementID) REFERENCES Element_Table(ID) ON DELETE CASCADE
);

CREATE TABLE Element_Table_Column(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	ElementID INT(6) NOT NULL,
	Text VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ElementID) REFERENCES Element_Table(ID) ON DELETE CASCADE
);

INSERT INTO Account VALUES('root', 'root', '', 'root', '', 'faculty');
INSERT INTO Account_Faculty VALUES('root', -1);