DROP DATABASE IF EXISTS Practicum;
CREATE DATABASE Practicum;
USE Practicum;

CREATE TABLE Account(
	Username VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	ContactNumber VARCHAR(20) NOT NULL,
	PRIMARY KEY(Username)
);

CREATE TABLE Company(
	Name VARCHAR(50) NOT NULL,
	MailingAddress VARCHAR(100) NOT NULL,
	PhoneNumber VARCHAR(20) NOT NULL,
	PRIMARY KEY(Name)
);

CREATE TABLE Account_Mentor(
	Username VARCHAR(50) NOT NULL,
	Company VARCHAR(50) NOT NULL,
	Title VARCHAR(50) NOT NULL,
	Department VARCHAR(50) NOT NULL,
	PRIMARY KEY(Username),
	FOREIGN KEY(Username) REFERENCES Account(Username),
	FOREIGN KEY(Company) REFERENCES Company(Name)
);

CREATE TABLE Account_Student(
	Username VARCHAR(50) NOT NULL,
	IDNumber INT(6) NOT NULL,
	Mentor VARCHAR(50) NOT NULL,
	Course VARCHAR(10) NOT NULL,
	PRIMARY KEY(Username),
	FOREIGN KEY(Username) REFERENCES Account(Username),
	FOREIGN KEY(Mentor) REFERENCES Account_Mentor(Username)
);

CREATE TABLE Account_Faculty(
	Username VARCHAR(50) NOT NULL,
	IDNumber INT(6) NOT NULL,
	PRIMARY KEY(Username),
	FOREIGN KEY(Username) REFERENCES Account(Username)
);

CREATE TABLE Form(
	ID INT(5) AUTO_INCREMENT NOT NULL,
	Name VARCHAR(100) NOT NULL,
	AccountPath VARCHAR(5) NOT NULL, 
	PRIMARY KEY(ID)
);

CREATE TABLE FormInstance(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	Username VARCHAR(50) NOT NULL,
	FormID INT(5) NOT NULL,
	Step INT(1) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(Username) REFERENCES Account_Student(Username),
	FOREIGN KEY(FormID) REFERENCES Form(ID)
);

CREATE TABLE Comments(
	ID INT(5) AUTO_INCREMENT NOT NULL,
	InstanceID INT(5) NOT NULL,
	FormStep INT(1) NOT NULL,
	Text VARCHAR(10000) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(InstanceID) REFERENCES FormInstance(ID)
);

CREATE TABLE Element(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	FormID INT(5) NOT NULL,
	ElementType VARCHAR(20) NOT NULL,
	Description VARCHAR(10000) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(FormID) REFERENCES Form(ID)
);

CREATE TABLE Answer(
	ElementID INT(6) NOT NULL,
	InstanceID INT(6) NOT NULL,
	Param1 INT(6) NOT NULL,
	Param2 INT(6) NOT NULL,
	Val VARCHAR(10000) NOT NULL,
	PRIMARY KEY(ElementID, InstanceID),
	FOREIGN KEY(ElementID) REFERENCES Element(ID),
	FOREIGN KEY(InstanceID) REFERENCES FormInstance(ID)
);

CREATE TABLE Element_PlainText(
	ID INT(6) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID)
);

CREATE TABLE Element_Field(
	ID INT(6) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	DefaultAnswer VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID)
);

CREATE TABLE Element_TextArea(
	ID INT(6) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	DefaultAnswer VARCHAR(10000) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID)
);

CREATE TABLE Element_DropDown(
	ID INT(6) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID)
);

CREATE TABLE Element_DropDown_Choice(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	ElementID INT(6) NOT NULL,
	Choice VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ElementID) REFERENCES Element_DropDown(ID)
);

CREATE TABLE Element_RadioCluster(
	ID INT(6) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID)
);

CREATE TABLE Element_RadioCluster_Section(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	ElementID INT(6) NOT NULL,
	HasButtons BOOLEAN NOT NULL,
	Text VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ElementID) REFERENCES Element_RadioCluster(ID)
);

CREATE TABLE Element_RadioCluster_Header(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	ElementID INT(6) NOT NULL,
	Text VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ElementID) REFERENCES Element_RadioCluster(ID)
);

CREATE TABLE Element_Table(
	ID INT(6) NOT NULL,
	HasRowText BOOLEAN NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID) REFERENCES Element(ID)
);

CREATE TABLE Element_Table_Row(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	ElementID INT(6) NOT NULL,
	Text VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ElementID) REFERENCES Element_Table(ID)
);

CREATE TABLE Element_Table_Column(
	ID INT(6) AUTO_INCREMENT NOT NULL,
	ElementID INT(6) NOT NULL,
	Text VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ElementID) REFERENCES Element_Table(ID)
);